In [1]:
#imports
import os

import numpy as np
import matplotlib.pyplot as plt

import pandas as pd
import librosa
import soundfile
import re
import cv2
from sklearn.model_selection import KFold

import IPython.display as ipd

import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras import Input, layers, optimizers, backend as K
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

In [22]:
#paths

model_path = "/Users/laurenogden/Downloads/gunshot_sound_model_multiclass.h5"

a_labels = "/Users/laurenogden/Downloads/gunshot_augmented_sound_labels_multiclass.npy"
a_samples = "/Users/laurenogden/Downloads/gunshot_augmented_sound_samples_multiclass.npy"

b_labels = "/Users/laurenogden/Downloads/gunshot_augmented_sound_labels_multiclass.npy"
b_samples = "/Users/laurenogden/Downloads/gunshot_augmented_sound_samples_multiclass.npy"

results = "/Users/laurenogden/Downloads/testing_results/"

results_guns = results +"guns/"

results_others = results+"others/"



In [9]:
labels = []
labels.append(3)
labels.append(2)
labels.append(1)
labels.append(3)
labels.append(0)


In [14]:
print(labels)

[3, 2, 1, 3, 0]


In [10]:
labels_np = keras.utils.to_categorical(labels, 4)

In [11]:
print(labels_np)

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


In [5]:
a = np.array([[0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1], [1, 0, 0, 0]])


In [6]:
print(a)
print(a.shape)

[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]
 [1 0 0 0]]
(5, 4)


In [18]:
b = np.argmax(labels_np, axis = 1)


In [19]:
print(b)
print(b.shape)

[3 2 1 3 0]
(5,)


In [20]:
for i in range(5):
    if labels[i] != b[i]:
        print(i)
    else:
        print("swag")

swag
swag
swag
swag
swag


In [21]:
diff = labels - b
print(diff)

[0 0 0 0 0]


In [ ]:

indexes = []
for i in range(len(diff)):
    if diff[i]!=0:
        indexes.append(i)
for ind in indexes:
    if label_np[ind]==1:
        direc = results_guns
    else:
        direc = results_others
    filepath = direc+"/"+str(ind)+".wav"
    print(filepath)
    librosa.output.write_wav(filepath,scont[ind],sr)